### PR TITLE
Feature/status script

### PR DESCRIPTION
**Pull request by riffy**
**Description:**
A little shell script that echoes the running / offline status of the service using systemctl.

**Background:**
Since I'm using Webmin to control the server, its easier for other people with custom commands instead of learning SSH.

If PR's are not welcome, let me know :)

KR

### CODE REVIEW

**Comment by A1RM4X** [comment]
Hi!

I am OK with the PR. 

I am not familiar with webmin, where is this executable supposed to be for being accessible to a webmin interface? Also what permission / user right should be defined for this script to work (need this info to update the tutorial)?

Thanks

**Comment by riffy** [comment]
Hi,

For the commands `systemctl is-active` and `systemctl status`, no elevated privileges need to be considered (only for other `start`, `stop`, `restart`, etc. which are not covered in this script).

This is basically a script for "new server owners" (which I assume are a lot out there with PalWorld :D ) to quickly check the server status without using the `systemctl` feature.

**One thing to note for the tutorial:**
`chmod +x ./status.sh` should be added to invoke the executable

About webmin:
Webmin allows for the workingdirectory and user / user environment to be set directly in the custom command (see picture), so it can be stored wherever (I've put it under /home/steam/commands/ )


webmin

webmin_0

webmin2


If required or wished, I could also make a PR for the Start / Stop scripts, but they require a setup step in the `visudo` to enable the `steam` group to control the `palworld.service` daemon, or make the service user-owned, so it can be changed without entering the password.

**Comment by Fortniter90** [comment]
Hey,

I'm new to making severs and I was wondering how to add the pal world sever to webmin.

Thanks

**Comment by A1RM4X** [comment]
> Hi,
> 
> For the commands `systemctl is-active` and `systemctl status`, no elevated privileges need to be considered (only for other `start`, `stop`, `restart`, etc. which are not covered in this script).
> 
> This is basically a script for "new server owners" (which I assume are a lot out there with PalWorld :D ) to quickly check the server status without using the `systemctl` feature.
> 
> **One thing to note for the tutorial:** `chmod +x ./status.sh` should be added to invoke the executable
> 
> About webmin: Webmin allows for the workingdirectory and user / user environment to be set directly in the custom command (see picture), so it can be stored wherever (I've put it under /home/steam/commands/ )
> 
> webmin
> 
> webmin_0
> 
> webmin2
> 
> If required or wished, I could also make a PR for the Start / Stop scripts, but they require a setup step in the `visudo` to enable the `steam` group to control the `palworld.service` daemon, or make the service user-owned, so it can be changed without entering the password.

Hey,

Sorry for the late answer, this flu is killing me...

I think it would be a nice option to the tutorial. Could you add to the PR an explanation within the README? If you want to, add it to the FAQ section for not adding complexity to the server installation itself.

Let me know what you think.

**Comment by riffy** [comment]
Hi @A1RM4X , @Fortniter90 

I've deviated from my plan and currently am developing a discrete [Palword Webmin Module](https://github.com/riffy/paldmin) . 
If you want to check it out, feel free to do so.

So from my perspective this PR can be closed or merged, either is fine by me.
 
Get well soon!

**Comment by A1RM4X** [comment]
Hey @riffy ! 

All good! Ping me up when you have a "final" version, I will add a link to your project in this README.

Cheers!

**Comment by riffy** [comment]
Hey @A1RM4X ,

I've just released the first version 1.0.0 https://github.com/riffy/paldmin , which possibly introduces a conflict, because I've integrated a cron-job scheduler for restarting, that may conflict with `RuntimeMaxSec` property by your service file 🙈. But all good.

We could maybe close this PR ?

KR

**Comment by perinazzoo** [comment]
hey @riffy , awesome work! I am setting up your paldmin version atm and have a question: is there anything I need to do with `RuntimeMaxSec` that isnt in the docs?

Update:

just removed `RuntimeMaxSec` and the webmin module worked like a charm!

**Pull request closed without merging**
