### PR TITLE
Feature: Backup on Server Shutdown

### PR DESCRIPTION
**Pull request by KuryKat**
> [!NOTE]
> Please merge #10 first

I feel like this is better because it saves the changes that have been made while the server was on, and in the case someone wants to do a rollback but still have a backup of the server as it was before the rollback.

I also updated the ``README-no.steam.md`` to include up-to-date script that weren't there, and a header that wasn't there.

I updated both ``README.md`` and ``README-no.steam.md`` to include the correct instructions for the new format.

I hope you like this update!

### CODE REVIEW

**Comment by A1RM4X** [comment]
If I understand it correctly the backup will happens when the server is still ON, while data is getting written on the files...

I did it the other way because I would like to avoid any corruption of the data saved. What are your thoughts about this?

**Comment by KuryKat** [comment]
That is true and I'm sorry for not realizing, after a little research I found this on the ``systemd`` manual:

> It is recommended to use this setting for commands that communicate with the service requesting clean termination. For post-mortem clean-up steps use ``ExecStopPost=`` instead.

[Reference in the Manual](https://github.com/keszybz/systemd/blob/main/man/systemd.service.xml#L575) right below there's the manual for the ``ExecStopPost=``

So we should just use ``ExecStopPost=`` instead of ``ExecStop=`` and it should be fine! I will commit this change in a minute

**Comment by KuryKat** [comment]
We should note that unlike ``ExecStop=``, commands specified with ``ExecStopPost=`` are *also* invoked when a service failed to start up correctly and is shut down again, so this can cause some duplicate backups, but I don't think it should be a problem.

As long as we're not creating backups while data is still being written it should be fine.

**Comment by A1RM4X** [comment]
Thanks!

I am not used to github in general... Is it possible to push this PR on the dev branch of this repo? Like that I can test it on my server and then push when I confirm everything is OK in a real world scenario?

Let me know if it is too much work, I will figure it out differently.

**Comment by KuryKat** [comment]
There you go, now the base branch is ``dev``, I meant to make this way from the beginning but I didn't see it was on the ``main``

Also I'm sorry for the 4-day delay, I forgot to check my notifications on GitHub

Edit: you could also clone it from my repo!

**Comment by KuryKat** [comment]
Any news? ^^

**Comment by A1RM4X** [comment]
I am testing the server for the next couple of weeks. If OK I will merge your PR into main.

Thanks again for your contributions.

**Pull request merged**
